spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      auto-index-creation: true

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:your-fallback-secret-for-production-needs-override}
  expirationMs: ${JWT_EXPIRATIONMS:86400000}
